// 晋升模板（2026-09-16 画廊二轮甄选入选的 5 套重组款）：config 已冻结为独立字面量，
// 不再依赖 recomboCandidates 与其父本模板。由一次性脚本从画廊甄选结果生成。
import type { FrameTemplate } from '../composables/useTemplates'

export const PROMOTED_TEMPLATES: FrameTemplate[] = [
  {
    "id": "rc_ccd_wall",
    "name": "CCD时码·石墨展墙",
    "desc": "石墨灰展墙底承载复古 CCD 取景器日期戳，重暗角，电子取景的怀旧感",
    "group": "暗调影廊",
    "category": "frame",
    "builtin": true,
    "config": {
      "bgMode": "blur",
      "blur": 0,
      "padding": 0,
      "borderRatio": 0,
      "photoRadius": 0,
      "borderRadius": 0,
      "scale": 100,
      "shadow": 0,
      "frameRatio": null,
      "infoLayout": "classic",
      "overlayAlign": "right",
      "overlayBottom": 46,
      "showLogo": false,
      "showCameraModel": false,
      "showExif": false,
      "showLens": false,
      "showDate": true,
      "dateFormat": "date",
      "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
      "fontSize": 30,
      "textWeight": 700,
      "textOpacity": 1,
      "dateTextColor": "#FFB43B",
      "bgColor": "#2B2D30",
      "borderColor": "#2B2D30",
      "vignette": 0
    }
  },
  {
    "id": "rc_slide_blur",
    "name": "幻灯片框·模糊延展",
    "desc": "幻灯片纸框浮在照片色调延展的模糊底上，胶片放映的仪式感",
    "group": "胶片复古",
    "category": "frame",
    "builtin": true,
    "config": {
      "bgMode": "blur",
      "bgColor": "#F1EDE2",
      "borderColor": "#F1EDE2",
      "padding": 0,
      "borderRatio": 0,
      "photoRadius": 3,
      "borderRadius": 0,
      "scale": 100,
      "shadow": 0,
      "frameRatio": 1,
      "infoLayout": "classic",
      "overlayAlign": "center",
      "overlayBottom": 20,
      "showLogo": false,
      "showCameraModel": false,
      "showExif": false,
      "showLens": false,
      "showDate": false,
      "vignette": 0,
      "grain": 0,
      "showWatermark": false,
      "infoLayer": {
        "enabled": true,
        "bindTarget": "canvas",
        "elements": [
          {
            "id": "el-sm-label",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": 62,
            "anchorX": "center",
            "anchorY": "top",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.9,
            "text": "FRAMELAB COLOR SLIDE",
            "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
            "fontSize": 27,
            "fontWeight": 600,
            "color": "#6C6455",
            "align": "center",
            "letterSpacing": 8,
            "lineHeight": 1.2
          },
          {
            "id": "el-sm-rule",
            "type": "divider",
            "enable": true,
            "x": 0,
            "y": 105,
            "anchorX": "center",
            "anchorY": "top",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.75,
            "width": 972,
            "thickness": 1,
            "color": "#C9BFA8"
          },
          {
            "id": "el-sm-date",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": -76,
            "anchorX": "left",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.85,
            "text": "SEP. 2026",
            "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
            "fontSize": 22,
            "fontWeight": 500,
            "color": "#6C6455",
            "align": "left",
            "letterSpacing": 4,
            "lineHeight": 1.2
          },
          {
            "id": "el-sm-stock",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": -76,
            "anchorX": "center",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.7,
            "text": "DAYLIGHT · 100",
            "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
            "fontSize": 19,
            "fontWeight": 500,
            "color": "#6C6455",
            "align": "center",
            "letterSpacing": 7,
            "lineHeight": 1.2
          },
          {
            "id": "el-sm-ref",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": -76,
            "anchorX": "right",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.85,
            "text": "REF. 25-0915",
            "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
            "fontSize": 22,
            "fontWeight": 500,
            "color": "#6C6455",
            "align": "right",
            "letterSpacing": 4,
            "lineHeight": 1.2
          }
        ]
      }
    }
  },
  {
    "id": "rc_poem_autumn",
    "name": "诗行·秋日米黄",
    "desc": "秋日米黄纸面承载诗行排版与暖灰小字，安静的文字向设计",
    "group": "创意排版",
    "category": "frame",
    "builtin": true,
    "config": {
      "bgMode": "solid",
      "bgColor": "#F4EFE4",
      "borderColor": "#F4EFE4",
      "padding": 81,
      "borderRatio": 405,
      "photoRadius": 2,
      "borderRadius": 0,
      "scale": 100,
      "shadow": 0,
      "frameRatio": null,
      "infoLayout": "classic",
      "overlayAlign": "center",
      "overlayBottom": 24,
      "showLogo": false,
      "showCameraModel": false,
      "showExif": false,
      "showLens": false,
      "showDate": false,
      "vignette": 0,
      "grain": 0,
      "showWatermark": false,
      "infoLayer": {
        "enabled": true,
        "bindTarget": "canvas",
        "elements": [
          {
            "id": "el-pm-poem",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": -256,
            "anchorX": "center",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.95,
            "text": "黄昏把湖面染成你的颜色，\n于是风也慢了下来。",
            "fontFamily": "'KaiTi', 'Kaiti SC', serif",
            "fontSize": 26,
            "fontWeight": 400,
            "color": "#4A4438",
            "align": "center",
            "letterSpacing": 4,
            "lineHeight": 1.9
          },
          {
            "id": "el-pm-rule",
            "type": "divider",
            "enable": true,
            "x": 0,
            "y": -162,
            "anchorX": "center",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.85,
            "width": 162,
            "thickness": 1,
            "color": "#CFC6B4"
          },
          {
            "id": "el-pm-sign",
            "type": "text",
            "enable": true,
            "x": 0,
            "y": -113,
            "anchorX": "center",
            "anchorY": "bottom",
            "scale": 1,
            "rotate": 0,
            "zIndex": 1,
            "exportable": true,
            "opacity": 0.85,
            "text": "黄昏手记 · 2026",
            "fontFamily": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
            "fontSize": 18,
            "fontWeight": 500,
            "color": "#8C8474",
            "align": "center",
            "letterSpacing": 4,
            "lineHeight": 1.2
          }
        ]
      }
    }
  },
  {
    "id": "rc_ticket_guide",
    "name": "入场券·展签灰白",
    "desc": "白底黑字的撕线票根造型，展览入场券式的信息排布",
    "group": "创意排版",
    "category": "frame",
    "builtin": true,
    "config": {
      "bgMode": "solid",
      "bgColor": "#FFFFFF",
      "borderColor": "#FFFFFF",
      "padding": 46,
      "borderRatio": 230,
      "photoRadius": 6,
      "borderRadius": 0,
      "scale": 90,
      "shadow": 0.15,
      "frameRatio": null,
      "infoLayout": "classic",
      "overlayAlign": "left",
      "overlayBottom": 26,
      "showLogo": false,
      "showCameraModel": false,
      "showExif": false,
      "showLens": false,
      "showDate": true,
      "dateFormat": "date",
      "dateFontSize": 20,
      "dateTextWeight": 500,
      "dateTextOpacity": 0.9,
      "fontSize": 20,
      "textWeight": 500,
      "textOpacity": 1,
      "vignette": 0,
      "grain": 0,
      "showWatermark": true,
      "watermarkText": "THIS STATION · CHENG DU",
      "watermarkTile": false,
      "watermarkOpacity": 0.92,
      "watermarkSize": 7,
      "watermarkAngle": 0,
      "watermarkAlign": "left",
      "watermarkBottom": 52
    }
  },
  {
    "id": "rc_leica_black",
    "name": "竖排参数·纯黑",
    "desc": "纯黑底上右缘竖排拍摄参数，极简锐利",
    "group": "暗调影廊",
    "category": "frame",
    "builtin": true,
    "config": {
      "bgMode": "blur",
      "blur": 0,
      "padding": 0,
      "borderRatio": 0,
      "photoRadius": 0,
      "borderRadius": 0,
      "scale": 100,
      "shadow": 0,
      "frameRatio": null,
      "infoLayout": "vertical",
      "overlayAlign": "center",
      "overlayBottom": 30,
      "showLogo": false,
      "showCameraModel": true,
      "cameraModelSize": 32,
      "cameraModelWeight": 600,
      "showExif": true,
      "showLens": false,
      "showDate": true,
      "dateFormat": "dash",
      "dateFontSize": 22,
      "dateTextWeight": 400,
      "dateTextOpacity": 0.75,
      "fontSize": 24,
      "textWeight": 500,
      "textOpacity": 1,
      "vignette": 0,
      "grain": 0,
      "showWatermark": false,
      "bgColor": "#000000",
      "borderColor": "#000000"
    }
  }
]
